//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ematig_Portal.Models.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmatigBbContext : DbContext
    {
        public EmatigBbContext()
            : base("name=EmatigBbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<MessageChannel> MessageChannel { get; set; }
        public virtual DbSet<MessageType> MessageType { get; set; }
        public virtual DbSet<MessageTypeDestination> MessageTypeDestination { get; set; }
        public virtual DbSet<MessageTypeMessageChannel> MessageTypeMessageChannel { get; set; }
        public virtual DbSet<Settings> Settings { get; set; }
    }
}
