//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ematig_Portal.Models.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageTypeMessageChannel
    {
        public short MessageTypeId { get; set; }
        public short MessageChannelId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
    
        public virtual MessageChannel MessageChannel { get; set; }
        public virtual MessageType MessageType { get; set; }
    }
}
