//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ematig_Portal.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageType : DomainObject
    {
        public MessageType()
        {
            this.Message = new HashSet<Message>();
            this.MessageTypeDestination = new HashSet<MessageTypeDestination>();
            this.MessageTypeMessageChannel = new HashSet<MessageTypeMessageChannel>();
        }
    
        public short Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<MessageTypeDestination> MessageTypeDestination { get; set; }
        public virtual ICollection<MessageTypeMessageChannel> MessageTypeMessageChannel { get; set; }
    }
}
